%dev.quarkus.datasource.jdbc.url=jdbc:h2:./.local-db/customer-db
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:customers
%prod.quarkus.datasource.jdbc.url=${DB_URL}
%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%dev.quarkus.hibernate-orm.log.sql=true
%test.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.schema-management.strategy=update
%test.quarkus.hibernate-orm.schema-management.strategy=update
%prod.quarkus.hibernate-orm.schema-management.strategy=validate
# Ältere Quarkus-Version:
# quarkus.hibernate-orm.database.generation=update